CREATE TABLE DESTINATION (
	DEST_NO	NUMBER	NOT NULL,
    DEST_CATEGORY	VARCHAR2(50)	NULL,
	DEST_SUBJECT	VARCHAR2(255)	NULL,
	DEST_SUMMARY	VARCHAR2(100)	NULL,
	DEST_CONTENT	VARCHAR2(1000)	NULL,
	DEST_ADDRESS	VARCHAR2(50)	NULL,
	DEST_MAP_X	NUMBER	NULL,
	DEST_MAP_Y	NUMBER	NULL,
	DEST_LIKE_SUM	NUMBER	NULL
	DEST_RATING_AVG	NUMBER	NULL,
	DEST_HIT	NUMBER	NULL,
	DEST_CREATEDATE	DATE	NULL,
	DEST_UPDATEDATE	DATE	NULL
);
DROP TABLE MY_PLANNER;
CREATE TABLE MY_PLANNER (
	P_NO	NUMBER	NOT NULL,
	P_PLACE	VARCHAR2(1000)	NULL,
	P_STARTDATE	DATE	NULL,
	P_ENDDATE	DATE	NULL,
	P_LT	DATE	NULL,
	P_MAP_X	NUMBER	NULL,
	P_MAP_Y	NUMBER	NULL,
	P_MAP	VARCHAR2(1000)	NULL,
	P_LIKE	VARCHAR2(10)	NULL,
	P_STATUS	VARCHAR2(1)	NULL,
	P_TYPE	VARCHAR2(1)	NULL,
	DEST_NO	NUMBER	NOT NULL,
	M_NO	NUMBER	NOT NULL,
	LOCATION_ID	NUMBER	NOT NULL
);

CREATE TABLE WITHDUK (
	WITH_NO	NUMBER	NOT NULL,
	WITH_MEM_NO	NUMBER	NOT NULL,
	WITH_WRITER_NICK	VARCHAR2(1000)	NULL,
	WITH_LOCATION	VARCHAR2(2000)	NULL,
	WITH_GENDER	VARCHAR2(10)	NULL,
	WITH_PERSONNER	NUMBER	NULL,
	WITH_STATUS	VARCHAR2(100)	NULL,
	WITH_PICTURE	VARCHAR2(3000)	NULL,
	WITH_TITLE	VARCHAR2(1000)	NULL,
	WITH_CONTENT	VARCHAR2(1000)	NULL,
	WITH_KEYWORD	VARCHAR2(1000)	NULL,
	WITH_READCOUNT	NUMBER	NULL,
	WITH_CREATEDATE	VARCHAR2(1000)	NULL,
	WITH_UPDATEDATE	VARCHAR2(1000)	NULL
);

CREATE TABLE WITHDUK_CHAT (
	CHAT_NO	NUMBER	NOT NULL,
	WITH_NO	NUMBER	NOT NULL,
    WITH_CATEGORY	VARCHAR2(1000)	NULL,
	CHAT_CONTENT	VARCHAR2(1000)	NULL,
	CHAT_TIME	VARCHAR2(1000)	NULL,
	CHAT_MEMNICK	VARCHAR2(1000)	NULL,
	WITH_MEM_NO	NUMBER	NOT NULL
);

CREATE TABLE MEMBER (
	M_NO	NUMBER	NOT NULL,
	M_ID	VARCHAR2(500)	NULL,
	M_PW	NUMBER	NULL,
	M_NAME	VARCHAR2(500)	NULL,
	M_NICKNAME	VARCHAR2(500)	NULL,
	M_EMAIL	VARCHAR2(500)	NULL,
	M_IS	VARCHAR2(20)	NULL,
	M_TYPE	VARCHAR2(20)	NULL,
	M_WARNING	NUMBER	NULL,
	M_STATUS	CHAR	NULL,
	M_AUTHORIZATION	CHAR	NULL
);

CREATE TABLE MEMBER_OUT (
	M_NO	NUMBER	NOT NULL,
	OUT_REASONS	NUMBER	NULL
);

CREATE TABLE DESTINATION_LIKE (
	DEST_NO	NUMBER	NOT NULL,
	M_NO	NUMBER	NOT NULL
);

CREATE TABLE DESTINATION_COMMENTS (
	COMMENTS_ID	NUMBER	NOT NULL,
	M_NO	NUMBER	NOT NULL,
	COMMENTS_WRITER_ID	VARCHAR2(20)	NULL,
	COMMENTS_WRITER_PW	VARCHAR(50)	NULL,
	COMMENTS_CONTENT	VARCHAR(500)	NULL,
	COMMENTS_RATING	NUMBER	NULL,
	COMMENTS_CREATEDATE	DATE	NULL,
	COMMENTS_UPDATEDATE	DATE	NULL,
	COMMENTS_IP_ADDRESS	VARCHAR2(15)	NULL,
	DEST_NO	NUMBER	NOT NULL
);

CREATE TABLE LIKE_PLANNER (
	P_NO	NUMBER	NOT NULL,
	M_NO	NUMBER	NOT NULL
);

CREATE TABLE LOCATION (
	LOCATION_ID	NUMBER	NOT NULL,
	LOCATION VARCHAR2(1000)	NULL
);

ALTER TABLE DESTINATION ADD CONSTRAINT PK_DESTINATION PRIMARY KEY (
	DEST_NO
);

ALTER TABLE MY_PLANNER ADD CONSTRAINT PK_MY_PLANNER PRIMARY KEY (
	P_NO
);

ALTER TABLE WITHDUK ADD CONSTRAINT PK_WITHDUK PRIMARY KEY (
	WITH_NO,
	WITH_MEM_NO
);

ALTER TABLE WITHDUK_CHAT ADD CONSTRAINT PK_WITHDUK_CHAT PRIMARY KEY (
	CHAT_NO
);

ALTER TABLE MEMBER ADD CONSTRAINT PK_MEMBER PRIMARY KEY (
	M_NO
);

ALTER TABLE MEMBER_OUT ADD CONSTRAINT PK_MEMBER_OUT PRIMARY KEY (
	M_NO
);

ALTER TABLE DESTINATION_LIKE ADD CONSTRAINT PK_DESTINATION_LIKE PRIMARY KEY (
	DEST_NO
);

ALTER TABLE DESTINATION_COMMENTS ADD CONSTRAINT PK_DESTINATION_COMMENTS PRIMARY KEY (
	COMMENTS_ID,
	M_NO
);

ALTER TABLE LIKE_PLANNER ADD CONSTRAINT PK_LIKE_PLANNER PRIMARY KEY (
	P_NO,
	M_NO
);

ALTER TABLE LOCATION ADD CONSTRAINT PK_LOCATION PRIMARY KEY (
	LOCATION_ID
);

ALTER TABLE WITHDUK ADD CONSTRAINT FK_MEMBER_TO_WITHDUK_1 FOREIGN KEY (
	WITH_MEM_NO
)
REFERENCES MEMBER (
	M_NO
);

ALTER TABLE MEMBER_OUT ADD CONSTRAINT FK_MEMBER_TO_MEMBER_OUT_1 FOREIGN KEY (
	M_NO
)
REFERENCES MEMBER (
	M_NO
);

ALTER TABLE DESTINATION_LIKE ADD CONSTRAINT FK_DESTINATION_TO_DESTINATION_LIKE_1 FOREIGN KEY (
	DEST_NO
)
REFERENCES DESTINATION (
	DEST_NO
);

ALTER TABLE DESTINATION_COMMENTS ADD CONSTRAINT FK_MEMBER_TO_DESTINATION_COMMENTS_1 FOREIGN KEY (
	M_NO
)
REFERENCES MEMBER (
	M_NO
);

ALTER TABLE LIKE_PLANNER ADD CONSTRAINT FK_MY_PLANNER_TO_LIKE_PLANNER_1 FOREIGN KEY (
	P_NO
)
REFERENCES MY_PLANNER (
	P_NO
);

ALTER TABLE LIKE_PLANNER ADD CONSTRAINT FK_MEMBER_TO_LIKE_PLANNER_1 FOREIGN KEY (
	M_NO
)
REFERENCES MEMBER (
	M_NO
);

